---------------------------------------1----------------------------------------
--FACULTY
--GROUPS
--STUDENT
--PROGRESS
--Выводятся специальность, дисциплины и средние оценки при сдаче экзаменов на факультете ТОВ.

SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(NOTE) AS [Средняя оценка], FACULTY.FACULTY
FROM FACULTY
	INNER JOIN GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY
	INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
	INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY = 'ТОВ'
GROUP BY ROLLUP(GROUPS.PROFESSION, 
				 PROGRESS.SUBJECT), FACULTY.FACULTY

--------------------------------------------------------------------------------

---------------------------------------2----------------------------------------
--FACULTY
--GROUPS
--STUDENT
--PROGRESS
--Выводятся специальность, дисциплины и средние оценки при сдаче экзаменов на факультете ТОВ.

SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(NOTE) AS [Средняя оценка], FACULTY.FACULTY
FROM FACULTY
	INNER JOIN GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY
	INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
	INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY = 'ТОВ'
GROUP BY CUBE(GROUPS.PROFESSION, 
				 PROGRESS.SUBJECT), FACULTY.FACULTY

--------------------------------------------------------------------------------


---------------------------------------3----------------------------------------
--FACULTY
--GROUPS
--STUDENT
--PROGRESS
--Выводятся специальность, дисциплины и средние оценки при сдаче экзаменов на факультете ТОВ.

SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(NOTE AS float(1))), 2) as [Средняя оценка], FACULTY.FACULTY
FROM FACULTY
	INNER JOIN GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY
	INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
	INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY = 'ТОВ'
GROUP BY GROUPS.PROFESSION, FACULTY.FACULTY, PROGRESS.SUBJECT
UNION
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(NOTE AS float(1))), 2) as [Средняя оценка], FACULTY.FACULTY
FROM FACULTY
	INNER JOIN GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY
	INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
	INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY = 'ХТиТ'
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY


SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(NOTE AS float(1))), 2) as [Средняя оценка], FACULTY.FACULTY
FROM FACULTY
	INNER JOIN GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY
	INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
	INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY = 'ТОВ'
GROUP BY GROUPS.PROFESSION, FACULTY.FACULTY, PROGRESS.SUBJECT
UNION ALL
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(NOTE AS float(1))), 2) as [Средняя оценка], FACULTY.FACULTY
FROM FACULTY
	INNER JOIN GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY
	INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
	INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY = 'ХТиТ'
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY
--------------------------------------------------------------------------------

---------------------------------------4-5----------------------------------------

SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(NOTE AS float(1))), 2) as [Средняя оценка], FACULTY.FACULTY
FROM FACULTY
	INNER JOIN GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY
	INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
	INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY = 'ТОВ'
GROUP BY GROUPS.PROFESSION, FACULTY.FACULTY, PROGRESS.SUBJECT
INTERSECT
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(NOTE AS float(1))), 2) as [Средняя оценка], FACULTY.FACULTY
FROM FACULTY
	INNER JOIN GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY
	INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
	INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY = 'ХТиТ'
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY

SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(NOTE AS float(1))), 2) as [Средняя оценка], FACULTY.FACULTY
FROM FACULTY
	INNER JOIN GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY
	INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
	INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY = 'ТОВ'
GROUP BY GROUPS.PROFESSION, FACULTY.FACULTY, PROGRESS.SUBJECT
EXCEPT 
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(NOTE AS float(1))), 2) as [Средняя оценка], FACULTY.FACULTY
FROM FACULTY
	INNER JOIN GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY
	INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
	INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY = 'ХТиТ'
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY

--------------------------------------------------------------------------------