--tasks 6,7

alter session set "_ORACLE_SCRIPT"=TRUE;
COMMIT;

revoke DBA from U1_KNV_PDB_USE;
GRANT DBA TO U1_KNV_PDB_USE;
revoke create any table FROM U1_KNV_PDB_USE;
COMMIT;

create  tablespace TS_KNV_PDB
    datafile 'ts_KNV_pdb1.dbf'
    size 7m
    autoextend on next 5m
    maxsize 20m
    extent management local;

create temporary tablespace TS_KNV_PDB_TEMP
    tempfile 'ts_KNV_pdb_temp1.dbf'
    size 5m
    autoextend on NEXT 3m
    maxsize 30m
    extent management local;
COMMIT;

select file_name, tablespace_name,status from dba_data_files
union
select FILE_NAME,TABLESPACE_NAME,status from DBA_TEMP_FILES;

create role  RL_KNVCORE_DEF;
select * from dba_roles where ROLE like '%RL%';

grant create session, create any table, create table, create view, create procedure to RL_KNVCORE_DEF;

select * from DBA_SYS_PRIVS where GRANTEE='RL_KNVCORE_DEF';
COMMIT;

create profile U1_KNV_PDB LIMIT
    password_life_time 180
    sessions_per_user 3
    failed_login_attempts 7
    password_lock_time 1
    password_reuse_time 10
    password_grace_time default
    connect_time 180
    idle_time 30;
COMMIT;
select * from DBA_PROFILES where PROFILE = 'U1_KNV_PDB';

create user U1_KNV_PDB_USE identified by 123321
default tablespace TS_KNV_PDB quota unlimited on TS_KNV_PDB
temporary tablespace TS_KNV_PDB_TEMP
profile U1_KNV_PDB
account unlock;

grant RL_KNVCORE_DEF to U1_KNV_PDB_USE;
commit;

---
drop user U1_KNV_PDB;

-- conn c##knv/booble34@//localhost:1521/KNV_PDB3 as sysdba


COMMIT;
create table KNV_table
(
    id  number(3) generated by default as identity primary key,
    name varchar2(10)
);
--8
SELECT role, granted_role, admin_option
FROM dba_roles, dba_role_privs
WHERE dba_roles.role = dba_role_privs.granted_role;
--
SELECT profile
FROM dba_profiles;
--
SELECT * FROM DBA_ROLE_PRIVS;
commit;
--9
