BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Faculty] (
    [FACULTY] VARCHAR(10) NOT NULL,
    [FACULTY_NAME] VARCHAR(50),
    CONSTRAINT [Faculty_pkey] PRIMARY KEY CLUSTERED ([FACULTY])
);

-- CreateTable
CREATE TABLE [dbo].[Pulpit] (
    [PULPIT] VARCHAR(10) NOT NULL,
    [PULPIT_NAME] VARCHAR(100),
    [FACULTY] VARCHAR(10) NOT NULL,
    CONSTRAINT [Pulpit_pkey] PRIMARY KEY CLUSTERED ([PULPIT])
);

-- CreateTable
CREATE TABLE [dbo].[Teacher] (
    [TEACHER] VARCHAR(10) NOT NULL,
    [TEACHER_NAME] VARCHAR(50),
    [PULPIT] VARCHAR(10) NOT NULL,
    CONSTRAINT [Teacher_pkey] PRIMARY KEY CLUSTERED ([TEACHER])
);

-- CreateTable
CREATE TABLE [dbo].[Subject] (
    [SUBJECT] VARCHAR(10) NOT NULL,
    [SUBJECT_NAME] VARCHAR(50) NOT NULL,
    [PULPIT] VARCHAR(10) NOT NULL,
    CONSTRAINT [Subject_pkey] PRIMARY KEY CLUSTERED ([SUBJECT])
);

-- CreateTable
CREATE TABLE [dbo].[AuditoriumType] (
    [AUDITORIUM_TYPE] VARCHAR(10) NOT NULL,
    [AUDITORIUM_TYPENAME] VARCHAR(30) NOT NULL,
    CONSTRAINT [AuditoriumType_pkey] PRIMARY KEY CLUSTERED ([AUDITORIUM_TYPE])
);

-- CreateTable
CREATE TABLE [dbo].[Auditorium] (
    [AUDITORIUM] VARCHAR(10) NOT NULL,
    [AUDITORIUM_NAME] VARCHAR(200),
    [AUDITORIUM_CAPACITY] INT,
    [AUDITORIUM_TYPE] VARCHAR(10) NOT NULL,
    CONSTRAINT [Auditorium_pkey] PRIMARY KEY CLUSTERED ([AUDITORIUM])
);

-- AddForeignKey
ALTER TABLE [dbo].[Pulpit] ADD CONSTRAINT [Pulpit_FACULTY_fkey] FOREIGN KEY ([FACULTY]) REFERENCES [dbo].[Faculty]([FACULTY]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[Teacher] ADD CONSTRAINT [Teacher_PULPIT_fkey] FOREIGN KEY ([PULPIT]) REFERENCES [dbo].[Pulpit]([PULPIT]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[Subject] ADD CONSTRAINT [Subject_PULPIT_fkey] FOREIGN KEY ([PULPIT]) REFERENCES [dbo].[Pulpit]([PULPIT]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[Auditorium] ADD CONSTRAINT [Auditorium_AUDITORIUM_TYPE_fkey] FOREIGN KEY ([AUDITORIUM_TYPE]) REFERENCES [dbo].[AuditoriumType]([AUDITORIUM_TYPE]) ON DELETE NO ACTION ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
