--Все препод с факультета хтит

SELECT *
FROM TEACHER
INNER JOIN (SELECT *
		    FROM PULPIT
			WHERE PULPIT.FACULTY = 'ЛХФ') AS XTIT ON TEACHER.PULPIT = XTIT.PULPIT


SELECT *
FROM TEACHER
WHERE TEACHER.PULPIT IN (SELECT PULPIT.PULPIT
                         FROM PULPIT
							INNER JOIN FACULTY ON PULPIT.FACULTY = FACULTY.FACULTY
						 WHERE FACULTY.FACULTY = 'ЛХФ')


--Кол-во препод на каждом факультете
SELECT COUNT(TEACHER.TEACHER_NAME), FACULTY.FACULTY
FROM TEACHER
	INNER JOIN PULPIT ON PULPIT.PULPIT = TEACHER.PULPIT
	INNER JOIN FACULTY ON PULPIT.FACULTY = FACULTY.FACULTY
GROUP BY FACULTY.FACULTY