--удалить предмет которые начинаются на букву п
SELECT SUBJECT.SUBJECT_NAME FROM SUBJECT WHERE SUBJECT_NAME LIKE 'О%';


DECLARE deleter CURSOR FOR SELECT SUBJECT.SUBJECT_NAME FROM SUBJECT WHERE SUBJECT_NAME LIKE 'О%';
OPEN deleter
	DECLARE @subject VARCHAR(300)
	FETCH NEXT FROM deleter into @subject
	DELETE SUBJECT WHERE CURRENT OF deleter
	WHILE @@FETCH_STATUS = 0
	BEGIN
		FETCH NEXT FROM deleter into @subject
		DELETE SUBJECT WHERE CURRENT OF deleter
	END	
CLOSE deleter
DEALLOCATE deleter


DECLARE deleter4 CURSOR FOR SELECT SUBJECT.SUBJECT_NAME FROM SUBJECT WHERE SUBJECT_NAME LIKE '%';
OPEN deleter4
	DECLARE @subject4 VARCHAR(300)
	FETCH NEXT FROM deleter4 into @subject4
	DELETE SUBJECT WHERE CURRENT OF deleter4
	WHILE @@FETCH_STATUS = 0
	BEGIN
		FETCH NEXT FROM deleter4 into @subject4
		DELETE SUBJECT WHERE CURRENT OF deleter4
	END	
CLOSE deleter4
DEALLOCATE deleter4

--удалить предмет которые начинаются на букву п
SELECT SUBJECT.SUBJECT_NAME FROM SUBJECT WHERE SUBJECT_NAME LIKE 'Т%';

DECLARE deleter2 CURSOR FOR SELECT SUBJECT.SUBJECT_NAME FROM SUBJECT;
OPEN deleter2
	DECLARE @subject2 VARCHAR(300)
	FETCH NEXT FROM deleter2 into @subject2
	DELETE SUBJECT WHERE CURRENT OF deleter2
	WHILE @@FETCH_STATUS = 0
	BEGIN
		FETCH NEXT FROM deleter2 into @subject2
		DELETE SUBJECT WHERE SUBJECT.SUBJECT_NAME LIKE 'Т%';
	END
CLOSE deleter2


--удалить предмет которые начинаются на букву п
SELECT SUBJECT.SUBJECT_NAME FROM SUBJECT WHERE SUBJECT_NAME LIKE 'Э%';

DECLARE deleter3 CURSOR FOR SELECT SUBJECT.SUBJECT_NAME FROM SUBJECT;
OPEN deleter3
	DECLARE @subject3 VARCHAR(300)
	FETCH NEXT FROM deleter3 into @subject3
	DELETE SUBJECT WHERE CURRENT OF deleter3
	WHILE @@FETCH_STATUS = 0
	BEGIN
		FETCH NEXT FROM deleter3 into @subject3
		DELETE SUBJECT WHERE SUBJECT.SUBJECT_NAME LIKE 'Э%';
	END
CLOSE deleter3

DECLARE deleter5 CURSOR FOR SELECT SUBJECT_NAME FROM SUBJECT WHERE PULPIT = 'ИСиТ';
OPEN deleter5
	DECLARE @subject5 VARCHAR(300)
	DECLARE @subjects5 VARCHAR(3000) = ''

	FETCH NEXT FROM deleter5 INTO @subject5
	SET @subjects5 = @subjects5 + @subject5 + ', ';
	WHILE @@FETCH_STATUS = 0
	BEGIN
		FETCH NEXT FROM deleter5 INTO @subject5
		SET @subjects5 = @subjects5 + @subject5 + ', ';
	END	
	PRINT @subjects5
CLOSE deleter5
DEALLOCATE deleter5
