version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: central_service_server
    ports:
      - "8000:8000" 
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./alembic:/app/alembic
      - ./src:/app/src
      - ./logs:/app/logs
    networks:
      - db_network
      - shared_network

  db:
    image: postgres:15-alpine 
    container_name: postgres_server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
  shared_network:
    external: true

volumes:
  postgres_data:
    driver: local
