SELECT *
FROM AUDITORIUM as AU
INNER JOIN AUDITORIUM_TYPE as AU_T ON AU.AUDITORIUM_TYPE = AU_T.AUDITORIUM_TYPE

---------------------------------------------------------------------------

SELECT  AUDITORIUM, AUDITORIUM_TYPENAME 
FROM AUDITORIUM  
JOIN AUDITORIUM_TYPE on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE AND AUDITORIUM_TYPENAME like '%[Êך]מלןü‏עונ%'

----------------------------------------------------------------------------
SELECT STUDENT.NAME, PROGRESS.NOTE, PROFESSION.PROFESSION_NAME, FACULTY.FACULTY, PULPIT.PULPIT_NAME, SUBJECT.SUBJECT,
CASE
	WHEN PROGRESS.NOTE = 6 THEN 'רוסעü'
	WHEN PROGRESS.NOTE = 7 THEN 'סולü'
	WHEN PROGRESS.NOTE = 8 THEN 'גמסולü'
END
FROM PROGRESS
JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT
JOIN STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
JOIN FACULTY ON FACULTY.FACULTY = GROUPS.FACULTY
JOIN PROFESSION ON PROFESSION.PROFESSION = GROUPS.PROFESSION
JOIN PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY
WHERE PROGRESS.NOTE BETWEEN 6 AND 8

-------------------------------------------------------

SELECT ISNULL(TEACHER.TEACHER_NAME, '***'), PULPIT.PULPIT_NAME
FROM PULPIT
LEFT JOIN TEACHER ON PULPIT.PULPIT = TEACHER.PULPIT

-------------------------------------------------------


SELECT *
FROM GROUPS
FULL OUTER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP

SELECT *
FROM STUDENT
FULL OUTER JOIN GROUPS ON GROUPS.IDGROUP = STUDENT.IDGROUP

SELECT *
FROM STUDENT 
FULL OUTER JOIN GROUPS ON GROUPS.IDGROUP = STUDENT.IDGROUP
WHERE GROUPS.IDGROUP IS NOT NULL;

SELECT *
FROM STUDENT 
FULL OUTER JOIN GROUPS ON GROUPS.IDGROUP = STUDENT.IDGROUP
WHERE STUDENT.IDGROUP IS  NULL;

-------------------------------------------------------

SELECT *
FROM AUDITORIUM CROSS JOIN AUDITORIUM_TYPE
WHERE AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE

-------------------------------------------------------

