version: '3'
services:
  webdav:
    image: bytemark/webdav
    restart: always
    ports:
      - "80:80"
    environment:
      AUTH_TYPE: Digest
      USERNAME: Glavnyi
      PASSWORD: hamster
    volumes:
      - /srv/dav:/var/lib/dav
