"""Initial migration

Revision ID: 9dc5bfae3836
Revises: 
Create Date: 2024-10-21 20:56:22.488284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dc5bfae3836'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bodi',
    sa.Column('IST', sa.String(length=3), nullable=False),
    sa.Column('TABL', sa.String(length=5), nullable=False),
    sa.Column('POK', sa.String(length=4), nullable=False),
    sa.Column('UT', sa.String(length=2), nullable=False),
    sa.Column('SUB', sa.String(length=6), nullable=False),
    sa.Column('OTN', sa.String(length=2), nullable=False),
    sa.Column('OBJ', sa.String(length=16), nullable=False),
    sa.Column('VID', sa.String(length=2), nullable=False),
    sa.Column('PER', sa.String(length=2), nullable=False),
    sa.Column('DATV', sa.DateTime(), nullable=False),
    sa.Column('DATV_SET', sa.DateTime(), nullable=False),
    sa.Column('ZNC', sa.Float(), nullable=False),
    sa.Column('PP', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('IST', 'TABL', 'POK', 'UT', 'SUB', 'OTN', 'OBJ', 'VID', 'PER', 'DATV_SET')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bodi')
    # ### end Alembic commands ###
